hydra:
  job_logging:
    formatters:
      simple:
        format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
    handlers:
      file:
        class: logging.FileHandler
        filename: ${hydra.job.name}.log
        formatter: simple
        level: INFO
      console:
        class: logging.StreamHandler
        formatter: simple
        level: INFO


experiment_name: "gnk" # Simulator name

num_repeat: 20            # Number of repetitions of the experiment

num_samples: 100000        # Number of training data samples

prior_mean: [0.0, 0.7, 0.0, -1.5]
prior_cov: [[5.0, 0.0, 0.0, 0.0], [0.0, 0.5, 0.0, 0.0], [0.0, 0.0, 4.0, 0.0], [0.0, 0.0, 0.0, 0.25]]

theta_true: [1.0, 0.5, 1.0, -1.]
n_obs: 100              # Number of observed data samples
n_obs_ref: 1000         # Number of observed data samples for the reference posterior

epsilon: 0.1                          # Percentage of outliers in the data
outlier_values: [-50.0]         # Position of the outliers

robust_flag: false

num_posterior_samples: 500            # Number of posterior samples
num_chains: 1 
warmup_steps: 500
thin: 1

beta_base_general: 1.0           # A reasonable starting value for beta for the general case
beta_base_case1: 0.1           # A reasonable starting value for beta for case 1
B: 100                   # Number of bootstrap samples
T: 20                    # Number of iterations when updating beta
alpha: 0.05              # 1-alpha credible set

hidden_dim: 128          # Hidden dimension of neural network used in case 1

d_x: 1


sr_num_samples_per_param: 15
sr_num_samples_per_param_boot: 7
sr_num_posterior_bootstrap: 200