# sir_undercounting.yaml
defaults:
  - sir
  - _self_
  
experiment_name: sir_undercounting
q: 0.5
robust_flag: false
sr_num_samples_per_param: 8
sr_num_samples_per_param_boot: 4
sr_num_posterior_bootstrap: 172